# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deKKo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs'
  source 'https://github.com/twilio/cocoapod-specs'
  # Pods for deKKo
  pod 'AFNetworking'
  pod 'Google/SignIn'
  pod 'MBProgressHUD'

  pod 'LFLiveKit'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'TwilioVideo', '1.0.0-beta12'



  target 'deKKoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'deKKoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
