# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deKKo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deKKo
  pod 'AFNetworking'
  pod 'Google/SignIn'
  pod 'MBProgressHUD'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'deKKoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'deKKoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
